export const POPULATE_TICKETS = 'POPULATE_TICKETS';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const RESTORE_TICKET = 'RESTORE_TICKET';
export const MARK_UNMARK_TICKET = 'MARK_UNMARK_TICKET';
export const APPLY_TICKET_MEMENTO = 'APPLY_TICKET_MEMENTO';
